// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  tutorialSidebar: [
    { type: 'autogenerated', dirName: '.' },
    {
      type: 'link',
      label: 'Storybook',
      href: 'https://storybook.h6s.dev',
    },
  ],
}
